### ISSUE TITLE
Start Without Button

### ISSUE THREAD

**Issue by TheByteSizeDev** [lijinke666/react-turntable#2]
Hey there!

I would love to use this for a project I'm doing but I want to get rid of the button and instead like to control when it spins through the code. How would I do this?

Thank you.

**Comment by lijinke666** [comment]
Hi~ later I released a new version adding 'hiddenButton' and `context` support you

**Comment by lijinke666** [comment]
upgarde `1.3.1`

[example](https://github.com/lijinke666/react-turntable/blob/master/example/example.js#L60)

```js
  <ReactTurntable
    {...options}
    hiddenButton
    getTurntable={turntable => (this.turntable = turntable)}
  />

  <button onClick={() => this.turntable.start()}>start</button>
  <button onClick={() => this.turntable.stop()}>stop</button>
```

**Comment by TheByteSizeDev** [comment]
You rock! Thank you.
